words = ["dream",
         "guard",
         "flood",
         "adult",
         "sight",
         "alarm",
         "force",
         "wound",
         "brave",
         "cable",
         "panic",
         "study",
         "faith",
         "equal",
         "grade",
         "award",
         "bully",
         "voice",
         "drive",
         "title"]

letters_in_words = [{'m', 'd', 'r', 'e', 'a'},
                    {'g', 'd', 'u', 'r', 'a'},
                    {'d', 'f', 'l', 'o'},
                    {'d', 'u', 'l', 't', 'a'},
                    {'h', 'i', 's', 't', 'g'},
                    {'m', 'l', 'r', 'a'},
                    {'f', 'c', 'r', 'o', 'e'},
                    {'w', 'n', 'd', 'u', 'o'},
                    {'b', 'v', 'r', 'e', 'a'},
                    {'b', 'e', 'c', 'l', 'a'},
                    {'n', 'i', 'p', 'c', 'a'},
                    {'d', 'u', 's', 't', 'y'},
                    {'h', 'f', 'i', 't', 'a'},
                    {'q', 'u', 'e', 'l', 'a'},
                    {'g', 'd', 'r', 'e', 'a'},
                    {'w', 'd', 'r', 'a'},
                    {'u', 'b', 'l', 'y'},
                    {'i', 'v', 'e', 'o', 'c'},
                    {'i', 'v', 'd', 'r', 'e'},
                    {'e', 'l', 'i', 't'}]

